# This file was generated by GoReleaser. DO NOT EDIT.
cask "somafm" do
  name "somafm"
  desc "Terminal-based music player for SomaFM radio stations"
  homepage "https://github.com/glebovdev/somafm-cli"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "somafm"

  on_macos do
    on_intel do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "3bbafb475d3b3dbb8c66a49cb9cbff06f9bd53bfabd51d49c30d411aca080def"
    end
    on_arm do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "8b2338b87e6ee0d3e62fdf39483f74d72de6f9c91c9b94294e327a452703bb6d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "007f5abbd3e6b4e36f67eb07f684ed7d40b79344f03f05d218c3c9365fc9543c"
    end
    on_arm do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "a79ae94479f1a619762542a615ba3b33e75674af138bb0bff8e9e6eccc93e507"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/somafm"]
    end
  end

  # No zap stanza required
end
