# This file was generated by GoReleaser. DO NOT EDIT.
cask "somafm" do
  name "somafm"
  desc "Terminal-based music player for SomaFM radio stations"
  homepage "https://github.com/glebovdev/somafm-cli"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "somafm"

  on_macos do
    on_intel do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "a6ec0e5f87e875f162b49cda84f1c19a96d28201a5a52bf6a0d60409b9ef4c72"
    end
    on_arm do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "9536bea3fb97f18a920c6fd25b1dd776cf0e779ea04aa5f17a5654d9eaee5716"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "3aba7a75c8be847547307a3cc8cd3b33906493b7a494f9c2fb51a97e38a6c001"
    end
    on_arm do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "a43b90912e6d6ec590af40f879ebd856ddef35c4092d8c065d5ea6d60e201740"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/somafm"]
    end
  end

  # No zap stanza required
end
