# This file was generated by GoReleaser. DO NOT EDIT.
cask "somafm" do
  name "somafm"
  desc "Terminal-based music player for SomaFM radio stations"
  homepage "https://github.com/glebovdev/somafm-cli"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "somafm"

  on_macos do
    on_intel do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "801ec78436b0c8522e31f97962ba47abf3664f96ceac382b85e502392305c9b9"
    end
    on_arm do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "82040c9b43192835dbc8cab46ef53ae8b4c5d95fec45086d15b61405260afce5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_linux_amd64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "52950be201d318620ba40624d92de7e4596da51f54878e728100608b85cb469b"
    end
    on_arm do
      url "https://github.com/glebovdev/somafm-cli/releases/download/v#{version}/somafm_#{version}_linux_arm64.tar.gz",
        verified: "github.com/glebovdev/somafm-cli"
      sha256 "f54d528a972631d78f94f58fb96dc8d1d9fb0b0f21a76e020f5efb0f4871853e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/somafm"]
    end
  end

  # No zap stanza required
end
